// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Foundation

public final class LogBrewClient: @unchecked Sendable {
    private let engine: DeliveryEngine
    private let baseContext: TelemetryContext?
    private let breadcrumbStore = IssueBreadcrumbStore()

    public static func create(
        apiKey: String,
        sdkName: String,
        sdkVersion: String,
        maxRetries: Int = 2,
        context: TelemetryContext? = nil,
        includeAutomaticContext: Bool = true,
    ) throws -> LogBrewClient {
        try LogBrewClient(
            config: ClientConfig(
                apiKey: apiKey,
                sdkName: sdkName,
                sdkVersion: sdkVersion,
                maxRetries: maxRetries,
                context: context,
                includeAutomaticContext: includeAutomaticContext,
            ),
        )
    }

    public init(config: ClientConfig) throws {
        try requireNonEmpty("api_key", config.apiKey)
        try requireNonEmpty("sdk_name", config.sdkName)
        try requireNonEmpty("sdk_version", config.sdkVersion)
        baseContext = try mergeTelemetryContexts(
            config.includeAutomaticContext ? automaticTelemetryContext() : nil,
            config.context,
        )
        engine = DeliveryEngine(
            apiKey: config.apiKey,
            sdk: SDKInfo(name: config.sdkName, language: "swift", version: config.sdkVersion),
            maxRetries: config.maxRetries,
        )
    }

    public func pendingEvents() -> Int {
        engine.pendingEvents()
    }

    public func previewJSON() throws -> String {
        try engine.previewJSON()
    }

    public func release(_ id: String, timestamp: String, attributes: ReleaseAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        try pushEvent(.release(validateRelease(attributes.withContext(context))), id: id, timestamp: timestamp)
    }

    public func environment(_ id: String, timestamp: String, attributes: EnvironmentAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        try pushEvent(.environment(validateEnvironment(attributes.withContext(context))), id: id, timestamp: timestamp)
    }

    public func issue(_ id: String, timestamp: String, attributes: IssueAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        let attributes = issueAttributes(attributes, adding: breadcrumbStore.snapshot())
            .withContext(context)
            .withCorrelationMetadata()
        try pushEvent(.issue(validateIssue(attributes)), id: id, timestamp: timestamp)
    }

    @_spi(CrashReplay)
    public func issueDetached(_ id: String, timestamp: String, attributes: IssueAttributes) throws {
        try pushEvent(.issue(validateIssue(attributes)), id: id, timestamp: timestamp)
    }

    public func log(_ id: String, timestamp: String, attributes: LogAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        try pushEvent(
            .log(validateLog(attributes.withContext(context).withCorrelationMetadata())),
            id: id,
            timestamp: timestamp,
        )
    }

    public func span(_ id: String, timestamp: String, attributes: SpanAttributes) throws {
        let inherited = try resolvedContext(event: attributes.context)
        let sampled = inherited?.trace.flatMap { trace in
            trace.traceId.caseInsensitiveCompare(attributes.traceId) == .orderedSame ? trace.sampled : nil
        }
        let spanTrace = telemetryTraceContext(
            traceId: attributes.traceId,
            spanId: attributes.spanId,
            parentSpanId: attributes.parentSpanId,
            sampled: sampled,
        )
        let context = try mergeTelemetryContexts(
            contextWithoutTrace(inherited),
            spanTrace.map { TelemetryContext(trace: $0) },
        )
        try pushEvent(.span(validateSpan(attributes.withContext(context))), id: id, timestamp: timestamp)
    }

    public func action(_ id: String, timestamp: String, attributes: ActionAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        try pushEvent(
            .action(validateAction(attributes.withContext(context).withCorrelationMetadata())),
            id: id,
            timestamp: timestamp,
        )
    }

    public func metric(_ id: String, timestamp: String, attributes: MetricAttributes) throws {
        let context = try resolvedContext(event: attributes.context)
        try pushEvent(
            .metric(validateMetric(attributes.withContext(context).withCorrelationMetadata())),
            id: id,
            timestamp: timestamp,
        )
    }

    /// Retain one validated breadcrumb for subsequent issues, evicting the oldest after 64 entries.
    public func addBreadcrumb(_ breadcrumb: IssueBreadcrumb) throws {
        try breadcrumbStore.add(breadcrumb)
    }

    /// Clear the client-owned breadcrumb history without changing already queued issues.
    public func clearBreadcrumbs() {
        breadcrumbStore.clear()
    }

    public func flush(transport: any Transport) throws -> TransportResponse {
        try engine.flush(transport: transport)
    }

    @_spi(CrashReplay)
    public func flushEvent(
        _ eventID: String,
        transport: any Transport,
    ) throws -> Bool {
        try requireNonEmpty("event id", eventID)
        return try engine.flushEvent(eventID, transport: transport)
    }

    public func shutdown(transport: any Transport) throws -> TransportResponse {
        try engine.shutdown(transport: transport)
    }

    public func startAutomaticDelivery(
        transport: any Transport,
        options: AutomaticDeliveryOptions = AutomaticDeliveryOptions(),
    ) throws {
        try engine.startAutomaticDelivery(transport: transport, options: options)
    }

    public func recoverAutomaticDelivery() throws {
        try engine.recoverAutomaticDelivery()
    }

    public func stopAutomaticDelivery() {
        engine.stopAutomaticDelivery()
    }

    public func deliveryHealth() -> DeliveryHealth {
        engine.health()
    }

    public func enableDurableDelivery(options: DurableDeliveryOptions) throws {
        try engine.enableDurableDelivery(options: options)
    }

    public func purgeDurableDelivery() throws {
        try engine.purgeDurableDelivery()
    }

    public func flush() throws -> TransportResponse {
        try engine.flushOwnedTransport()
    }

    public func shutdown() throws -> TransportResponse {
        try engine.shutdownOwnedTransport()
    }

    private func pushEvent(_ attributes: EventAttributes, id: String, timestamp: String) throws {
        try requireNonEmpty("event id", id)
        try requireTimestamp(timestamp)
        try engine.enqueue(Event(type: attributes.eventType, timestamp: timestamp, id: id, attributes: attributes))
    }

    private func resolvedContext(event: TelemetryContext?) throws -> TelemetryContext? {
        var context = try mergeTelemetryContexts(baseContext, LogBrewTelemetry.current)
        if let activeTrace = LogBrewTrace.current {
            context = try mergeTelemetryContexts(
                context,
                TelemetryContext(trace: telemetryTraceContext(activeTrace)),
            )
        }
        return try mergeTelemetryContexts(context, event)
    }
}

private extension IssueAttributes {
    func withContext(_ context: TelemetryContext?) -> IssueAttributes {
        IssueAttributes(
            title: title,
            level: level,
            message: message,
            exception: exception,
            stackFrames: stackFrames,
            breadcrumbs: breadcrumbs,
            breadcrumbsTruncated: breadcrumbsTruncated,
            metadata: metadata,
            context: context,
            nativeStackFrames: nativeStackFrames,
        )
    }

    func withCorrelationMetadata() -> IssueAttributes {
        IssueAttributes(
            title: title,
            level: level,
            message: message,
            exception: exception,
            stackFrames: stackFrames,
            breadcrumbs: breadcrumbs,
            breadcrumbsTruncated: breadcrumbsTruncated,
            metadata: correlationMetadata(metadata, context: context),
            context: context,
            nativeStackFrames: nativeStackFrames,
        )
    }
}

private extension LogAttributes {
    func withContext(_ context: TelemetryContext?) -> LogAttributes {
        LogAttributes(
            message: message,
            level: level,
            logger: logger,
            metadata: metadata,
            context: context,
        )
    }

    func withCorrelationMetadata() -> LogAttributes {
        LogAttributes(
            message: message,
            level: level,
            logger: logger,
            metadata: correlationMetadata(metadata, context: context),
            context: context,
        )
    }
}

private extension ActionAttributes {
    func withContext(_ context: TelemetryContext?) -> ActionAttributes {
        ActionAttributes(name: name, status: status, metadata: metadata, context: context)
    }

    func withCorrelationMetadata() -> ActionAttributes {
        ActionAttributes(
            name: name,
            status: status,
            metadata: correlationMetadata(metadata, context: context),
            context: context,
        )
    }
}

private extension MetricAttributes {
    func withContext(_ context: TelemetryContext?) -> MetricAttributes {
        MetricAttributes(
            name: name,
            kind: kind,
            value: value,
            unit: unit,
            temporality: temporality,
            metadata: metadata,
            context: context,
            description: description,
        )
    }

    func withCorrelationMetadata() -> MetricAttributes {
        MetricAttributes(
            name: name,
            kind: kind,
            value: value,
            unit: unit,
            temporality: temporality,
            metadata: correlationMetadata(metadata, context: context),
            context: context,
            description: description,
        )
    }
}

private extension ReleaseAttributes {
    func withContext(_ context: TelemetryContext?) -> ReleaseAttributes {
        ReleaseAttributes(version: version, commit: commit, notes: notes, metadata: metadata, context: context)
    }
}

private extension EnvironmentAttributes {
    func withContext(_ context: TelemetryContext?) -> EnvironmentAttributes {
        EnvironmentAttributes(name: name, region: region, metadata: metadata, context: context)
    }
}

private extension SpanAttributes {
    func withContext(_ context: TelemetryContext?) -> SpanAttributes {
        SpanAttributes(
            name: name,
            traceId: traceId,
            spanId: spanId,
            parentSpanId: parentSpanId,
            status: status,
            durationMs: durationMs,
            events: events,
            links: links,
            metadata: metadata,
            context: context,
        )
    }
}

private func correlationMetadata(_ metadata: Metadata?, context: TelemetryContext?) -> Metadata? {
    guard let trace = context?.trace else {
        return metadata
    }
    var output = metadata ?? [:]
    output["traceId"] = .string(trace.traceId)
    if let spanId = trace.spanId {
        output["spanId"] = .string(spanId)
    }
    if let parentSpanId = trace.parentSpanId {
        output["parentSpanId"] = .string(parentSpanId)
    }
    if let sampled = trace.sampled {
        output["traceSampled"] = .bool(sampled)
    }
    if let active = LogBrewTrace.current, active.traceId == trace.traceId, active.spanId == trace.spanId {
        output["traceFlags"] = .string(active.traceFlags)
    }
    return output
}

private func contextWithoutTrace(_ context: TelemetryContext?) -> TelemetryContext? {
    guard let context,
          context.resource != nil || context.session != nil || context.subject != nil || context.tags != nil
    else {
        return nil
    }
    return TelemetryContext(
        resource: context.resource,
        session: context.session,
        subject: context.subject,
        tags: context.tags,
    )
}
