// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Foundation
#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

public final class LogBrewURLSessionTracer: @unchecked Sendable {
    private let client: LogBrewClient
    private let dataLoader: @Sendable (URLRequest) async throws -> (Data, URLResponse)
    private let timestampProvider: @Sendable () -> String
    private let nowMsProvider: @Sendable () -> Double
    private let onCaptureError: (@Sendable (any Error) -> Void)?
    private let eventIDPrefix: String
    private let lock = NSLock()
    private var nextEventSequence = 1

    public convenience init(
        client: LogBrewClient,
        session: URLSession = .shared,
        eventIDPrefix: String = "evt_urlsession",
        timestampProvider: (@Sendable () -> String)? = nil,
        nowMsProvider: (@Sendable () -> Double)? = nil,
        onCaptureError: (@Sendable (any Error) -> Void)? = nil,
    ) throws {
        try self.init(
            client: client,
            eventIDPrefix: eventIDPrefix,
            timestampProvider: timestampProvider,
            nowMsProvider: nowMsProvider,
            onCaptureError: onCaptureError,
            dataLoader: { request in
                try await session.data(for: request)
            },
        )
    }

    init(
        client: LogBrewClient,
        eventIDPrefix: String = "evt_urlsession",
        timestampProvider: (@Sendable () -> String)? = nil,
        nowMsProvider: (@Sendable () -> Double)? = nil,
        onCaptureError: (@Sendable (any Error) -> Void)? = nil,
        dataLoader: @escaping @Sendable (URLRequest) async throws -> (Data, URLResponse),
    ) throws {
        let normalizedPrefix = eventIDPrefix.trimmingCharacters(in: .whitespacesAndNewlines)
        try requireNonEmpty("URLSession tracer eventIDPrefix", normalizedPrefix)
        self.client = client
        self.eventIDPrefix = normalizedPrefix
        self.timestampProvider = timestampProvider ?? currentTelemetryTimestamp
        self.nowMsProvider = nowMsProvider ?? Self.defaultNowMs
        self.onCaptureError = onCaptureError
        self.dataLoader = dataLoader
    }

    @discardableResult
    public func data(
        for request: URLRequest,
        routeTemplate: String? = nil,
        eventID: String? = nil,
        metadata: Metadata? = nil,
        onRequestError: (@Sendable (any Error) throws -> Void)? = nil,
    ) async throws -> (Data, URLResponse) {
        let span = try LogBrewTrace.startURLSessionSpan(for: request, routeTemplate: routeTemplate)
        let startedAtMs = nowMsProvider()

        do {
            let (data, response) = try await dataLoader(span.request)
            let durationMs = durationSince(startedAtMs)
            captureSpan(eventID, span: span, response: response, durationMs: durationMs, metadata: metadata)
            return (data, response)
        } catch {
            let durationMs = durationSince(startedAtMs)
            captureSpan(eventID, span: span, durationMs: durationMs, error: error, metadata: metadata)
            captureRequestError(error, context: span.traceContext, handler: onRequestError)
            throw error
        }
    }

    private func captureRequestError(
        _ requestError: any Error,
        context: LogBrewTraceContext,
        handler: (@Sendable (any Error) throws -> Void)?,
    ) {
        guard let handler else {
            return
        }
        capture {
            try LogBrewTrace.withContext(context) {
                try handler(requestError)
            }
        }
    }

    private func captureSpan(
        _ eventID: String?,
        span: LogBrewURLSessionSpan,
        response: URLResponse? = nil,
        durationMs: Double,
        error: (any Error)? = nil,
        metadata: Metadata?,
    ) {
        capture {
            try client.captureURLSessionSpan(
                eventID ?? nextEventID(),
                timestamp: timestampProvider(),
                span: span,
                statusCode: (response as? HTTPURLResponse)?.statusCode,
                durationMs: durationMs,
                error: error,
                metadata: metadata,
            )
        }
    }

    private func capture(_ operation: () throws -> Void) {
        do {
            try operation()
        } catch {
            onCaptureError?(error)
        }
    }

    private func durationSince(_ startedAtMs: Double) -> Double {
        let endedAtMs = nowMsProvider()
        guard startedAtMs.isFinite, endedAtMs.isFinite else {
            return 0
        }
        return max(0, endedAtMs - startedAtMs)
    }

    private func nextEventID() -> String {
        lock.withLock {
            let eventID = "\(eventIDPrefix)_\(nextEventSequence)"
            nextEventSequence += 1
            return eventID
        }
    }

    private static func defaultNowMs() -> Double {
        ProcessInfo.processInfo.systemUptime * 1000
    }
}
