// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import CryptoKit
import Foundation

struct CrashReportSanitizer {
    let maxReplayBytes: Int
    let ownerNonce: UUID

    func makeRecord(reportID: Int64, rawReport: [String: Any]) throws -> NativeCrashRecord {
        let data = try canonicalData(rawReport)
        guard let report = rawReport["report"] as? [String: Any],
              let rawID = report["id"] as? String,
              let uuid = UUID(uuidString: rawID),
              let rawTimestamp = report["timestamp"] as? String,
              let timestamp = NativeCrashTimestamp(rawTimestamp)
        else {
            throw NativeCrashError(.reportCorrupt)
        }

        let crash = rawReport["crash"] as? [String: Any]
        let error = crash?["error"] as? [String: Any]
        let nativeStackFrames = NativeStackFrameSanitizer().frames(from: rawReport)
        let artifactIdentity = try NativeArtifactIdentityValue.persistedIdentity(in: rawReport)
        return NativeCrashRecord(
            eventID: uuid.uuidString.lowercased(),
            timestamp: timestamp.normalized,
            mechanism: mechanism(error?["type"] as? String),
            nativeStackFrames: nativeStackFrames,
            artifactIdentity: artifactIdentity,
            hangState: nil,
            hangDurationMs: nil,
            source: .engine(reportID: reportID),
            digest: Data(SHA256.hash(data: data)),
            ownerNonce: ownerNonce,
        )
    }

    func digest(_ rawReport: [String: Any]) throws -> Data {
        try Data(SHA256.hash(data: canonicalData(rawReport)))
    }

    private func canonicalData(_ rawReport: [String: Any]) throws -> Data {
        guard JSONSerialization.isValidJSONObject(rawReport) else {
            throw NativeCrashError(.reportCorrupt)
        }
        do {
            let data = try JSONSerialization.data(withJSONObject: rawReport, options: [.sortedKeys])
            guard data.count <= maxReplayBytes else {
                throw NativeCrashError(.reportCorrupt)
            }
            return data
        } catch let error as NativeCrashError {
            throw error
        } catch {
            throw NativeCrashError(.reportCorrupt)
        }
    }

    private func mechanism(_ rawValue: String?) -> NativeCrashMechanism {
        switch rawValue {
        case "signal": .signal
        case "mach": .machException
        case "cpp_exception": .cppException
        case "nsexception": .objectiveCException
        case "memory_termination": .memoryTermination
        case "deadlock": .deadlock
        default: .unknown
        }
    }
}

struct NativeCrashTimestamp: Comparable {
    let normalized: String
    private let wholeSecond: String
    private let fractionalNanoseconds: String

    init?(_ raw: String) {
        guard raw.utf8.count <= 64,
              !raw.unicodeScalars.contains(where: CharacterSet.controlCharacters.contains),
              let components = Self.components(in: raw)
        else {
            return nil
        }

        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        guard let date = formatter.date(from: components.wholeSecond) else {
            return nil
        }
        wholeSecond = formatter.string(from: date)
        fractionalNanoseconds = components.fractional
            .padding(toLength: 9, withPad: "0", startingAt: 0)
        if components.fractional.isEmpty {
            normalized = wholeSecond
        } else {
            normalized = "\(wholeSecond.dropLast()).\(components.fractional)Z"
        }
    }

    static func < (lhs: NativeCrashTimestamp, rhs: NativeCrashTimestamp) -> Bool {
        if lhs.wholeSecond != rhs.wholeSecond {
            return lhs.wholeSecond < rhs.wholeSecond
        }
        return lhs.fractionalNanoseconds < rhs.fractionalNanoseconds
    }

    static func == (lhs: NativeCrashTimestamp, rhs: NativeCrashTimestamp) -> Bool {
        lhs.wholeSecond == rhs.wholeSecond
            && lhs.fractionalNanoseconds == rhs.fractionalNanoseconds
    }

    private static func components(in timestamp: String) -> (wholeSecond: String, fractional: String)? {
        guard let timeStart = timestamp.firstIndex(of: "T") else {
            return nil
        }
        guard let separator = timestamp[timeStart...].firstIndex(of: ".") else {
            return (timestamp, "")
        }
        let fractionalStart = timestamp.index(after: separator)
        let suffix = timestamp[fractionalStart...]
        let digits = suffix.prefix {
            $0 >= "0" && $0 <= "9"
        }
        guard (1 ... 9).contains(digits.count),
              let timezoneStart = timestamp.index(
                  fractionalStart,
                  offsetBy: digits.count,
                  limitedBy: timestamp.endIndex,
              )
        else {
            return nil
        }
        return (
            String(timestamp[..<separator] + timestamp[timezoneStart...]),
            String(digits),
        )
    }
}
