// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Darwin
import Foundation

@objc(LBRNAppleNativeCrashCapture)
@objcMembers
public final class NativeCrashCapture: NSObject, @unchecked Sendable {
    let configuration: NativeCrashConfiguration
    let driver: any CrashEngineDriving
    let ownership: ProcessCrashCaptureOwnership
    let processIDProvider: @Sendable () -> Int32
    let ownerProcessID: Int32
    let ownerNonce = UUID()
    let lock = NSLock()

    var store: (any CrashReportStoring)?
    var hangStore: (any HangIncidentStoring)?
    var hangRuntime: NativeHangWatchdogRuntime?
    var storageLease: CrashStorageLease?
    var lifecycle: NativeCrashLifecycleState = .idle
    var lastOutcome: NativeCrashOutcome = .none
    var acknowledged = 0
    var discarded = 0
    var replaying = false

    public init(configuration: NativeCrashConfiguration) {
        let processIDProvider: @Sendable () -> Int32 = { getpid() }
        self.configuration = configuration
        driver = KSCrashEngineDriver()
        ownership = .shared
        self.processIDProvider = processIDProvider
        ownerProcessID = processIDProvider()
        super.init()
    }

    init(
        configuration: NativeCrashConfiguration,
        driver: any CrashEngineDriving,
        ownership: ProcessCrashCaptureOwnership,
        processIDProvider: @escaping @Sendable () -> Int32 = { getpid() },
    ) {
        self.configuration = configuration
        self.driver = driver
        self.ownership = ownership
        self.processIDProvider = processIDProvider
        ownerProcessID = processIDProvider()
        super.init()
    }

    public func install() throws {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()

        if store != nil, lifecycle != .stopped {
            try verifyStorageLocked()
            return
        }
        if lifecycle == .stopped {
            throw NativeCrashError(.notInstalled)
        }
        if lifecycle == .failed {
            throw NativeCrashError(.engineInstallFailed)
        }

        do {
            let storageLease = try CrashStorageDirectory.prepare(configuration.storageDirectory)
            let preparedHang = try prepareHangWatchdog()
            try ownership.claim(self)
            try storageLease.verify()
            self.storageLease = storageLease
            let installedStore = try driver.install(
                configuration: CrashEngineConfiguration(
                    storageDirectory: configuration.storageDirectory,
                    maxStoredReports: configuration.maxStoredReports,
                    monitors: [.machException, .signal, .cppException, .objectiveCException],
                    includesMemory: false,
                    includesQueueNames: false,
                    includesConsoleLog: false,
                    artifactIdentity: configuration.artifactIdentity.map(NativeArtifactIdentityValue.init),
                    deletionIsExplicit: true,
                ),
            )
            try storageLease.verify()
            store = installedStore
            hangStore = preparedHang?.store
            hangRuntime = preparedHang?.runtime
            preparedHang?.runtime.start()
            lifecycle = .installed
        } catch let error as NativeCrashError {
            lifecycle = .failed
            lastOutcome = .failed
            throw error
        } catch {
            lifecycle = .failed
            lastOutcome = .failed
            throw NativeCrashError(.engineInstallFailed)
        }
    }

    public func pendingReports() throws -> [NativeCrashRecord] {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()
        return try pendingReportsLocked()
    }

    /// Replaces the crash-time trace, session, and opaque subject snapshot in one bounded write.
    @nonobjc
    public func setCorrelationContext(_ context: TelemetryContext?) throws {
        try setDiagnosticContext(context: context, impact: nil)
    }

    @nonobjc
    func setDiagnosticContext(
        context: TelemetryContext?,
        impact: IssueImpactEvidence?,
    ) throws {
        try setSnapshot(forKey: NativeCrashCorrelation.reportKey) {
            try NativeCrashCorrelation.encoded(context: context, impact: impact)
        }
    }

    /// Replaces the crash-time breadcrumb snapshot in one bounded write.
    @nonobjc
    public func setBreadcrumbs(
        _ breadcrumbs: [IssueBreadcrumb]?,
        truncated: Bool = false,
    ) throws {
        try setSnapshot(forKey: NativeCrashBreadcrumbs.reportKey) {
            try NativeCrashBreadcrumbs.encoded(breadcrumbs, truncated: truncated)
        }
    }

    private func setSnapshot(
        forKey key: String,
        encoded: () throws -> String?,
    ) throws {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()
        guard store != nil, lifecycle != .stopped else {
            throw NativeCrashError(.notInstalled)
        }
        try verifyStorageLocked()
        try driver.setUserInfo(encoded(), forKey: key)
    }

    @objc(replayPendingReportsWithHandler:error:)
    public func replayPendingReports(
        _ handler: (NativeCrashRecord) -> Bool,
    ) throws -> NativeCrashReplayResult {
        try beginReplay()
        do {
            return try performReplay(handler)
        } catch {
            failReplay()
            throw error
        }
    }

    /// Replays stored reports through the existing delivery engine and acknowledges only accepted reports.
    @nonobjc
    public func replayPendingReports(
        in client: LogBrewClient,
        transport: any Transport,
    ) throws -> NativeCrashReplayResult {
        try replayPendingReports { record in
            do {
                try record.enqueue(in: client)
                return try client.flushEvent(
                    record.eventID,
                    transport: transport,
                )
            } catch {
                return false
            }
        }
    }

    /// Stops replay through this adapter without claiming to uninstall the process-lifetime crash handler.
    public func stopReplay() throws {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()
        guard store != nil else {
            throw NativeCrashError(.notInstalled)
        }
        guard !replaying else {
            throw NativeCrashError(.replayBusy)
        }
        hangRuntime?.stop()
        lifecycle = .stopped
    }

    public func purge() throws {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()
        guard let store else {
            throw NativeCrashError(.notInstalled)
        }
        try verifyStorageLocked()
        guard !replaying else {
            throw NativeCrashError(.replayBusy)
        }

        store.deleteAllReports()
        guard store.reportIDs.isEmpty else {
            lastOutcome = .failed
            throw NativeCrashError(.reportDeletionFailed)
        }
        try hangStore?.purge()
        lastOutcome = .purged
    }

    public func status() throws -> NativeCrashStatus {
        lock.lock()
        defer { lock.unlock() }
        try verifyProcessLocked()
        let pending = store == nil ? 0 : try pendingCountLocked()
        return NativeCrashStatus(
            lifecycle: lifecycle,
            pending: pending,
            acknowledged: acknowledged,
            discarded: discarded,
            lastOutcome: lastOutcome,
        )
    }
}

extension NativeCrashCapture {
    func verifyStorageLocked() throws {
        guard let storageLease else {
            throw NativeCrashError(.notInstalled)
        }
        try storageLease.verify()
    }

    func verifyProcessLocked() throws {
        guard processIDProvider() == ownerProcessID else {
            throw NativeCrashError(.processChanged)
        }
    }
}

private extension NativeCrashCapture {
    func prepareHangWatchdog() throws -> PreparedHangWatchdog? {
        guard let watchdog = configuration.hangWatchdog,
              let identity = configuration.artifactIdentity
        else {
            return nil
        }
        let directory = configuration.storageDirectory
            .appendingPathComponent("hang-watchdog-v1", isDirectory: true)
        let store = try NativeHangIncidentFileStore(directory: directory)
        let runtime = try NativeHangWatchdogRuntime(
            configuration: watchdog,
            identity: identity,
            store: store,
        )
        return PreparedHangWatchdog(store: store, runtime: runtime)
    }
}

private struct PreparedHangWatchdog {
    let store: any HangIncidentStoring
    let runtime: NativeHangWatchdogRuntime
}
