// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.

func nativeCrashExceptionChain(for exception: IssueException) -> IssueExceptionChain {
    IssueExceptionChain(entries: [
        IssueExceptionChainEntry(
            id: 0,
            relationship: .reported,
            type: exception.type,
            messageState: .notCaptured,
            mechanism: exception.mechanism,
            stackFramesState: .notCaptured,
        ),
    ])
}
