// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Foundation

public enum NativeHangDiagnosticCode: String, Sendable {
    case skippedDebugger = "hang_skipped_debugger"
    case skippedThermal = "hang_skipped_thermal"
    case skippedSchedulerStall = "hang_skipped_scheduler_stall"
    case stackUnavailable = "hang_stack_unavailable"
    case storageFailed = "hang_storage_failed"
    case pendingRetained = "hang_pending_retained"
    case captured = "hang_captured"
    case recovered = "hang_recovered"
}

public struct NativeHangDiagnostic: Sendable, CustomStringConvertible {
    public let code: NativeHangDiagnosticCode

    init(_ code: NativeHangDiagnosticCode) {
        self.code = code
    }

    public var description: String {
        "NativeHangDiagnostic(code: \(code.rawValue))"
    }
}

public struct NativeHangWatchdogConfiguration: @unchecked Sendable {
    public let threshold: TimeInterval
    public let diagnosticsHandler: (@Sendable (NativeHangDiagnostic) -> Void)?

    public init(
        threshold: TimeInterval = 2,
        diagnosticsHandler: (@Sendable (NativeHangDiagnostic) -> Void)? = nil,
    ) throws {
        guard threshold.isFinite, (1 ... 30).contains(threshold) else {
            throw NativeCrashError(.invalidConfiguration)
        }
        self.threshold = threshold
        self.diagnosticsHandler = diagnosticsHandler
    }
}

protocol HangWatchdogClock: AnyObject, Sendable {
    func monotonicNow() -> TimeInterval
    func timestamp() -> String
}

protocol HangSafetyChecking: AnyObject, Sendable {
    func isDebuggerAttached() -> Bool
    func isThermallyRestricted() -> Bool
}

protocol MainThreadStackCapturing: AnyObject, Sendable {
    func capture() -> [NativeStackFrame]
}

protocol MainThreadPinging: AnyObject, Sendable {
    func ping(_ response: @escaping @Sendable () -> Void)
}

protocol HangDiagnosticDelivering: AnyObject, Sendable {
    func enqueue(_ diagnostic: NativeHangDiagnostic)
}

protocol HangWatchdogControlling: AnyObject, Sendable {
    func start(active: Bool)
    func setActive(_ active: Bool)
    func poll()
    func stop()
}

protocol HangTimerControlling: AnyObject, Sendable {
    func activate()
    func cancel()
}

protocol HangLifecycleObserving: AnyObject, Sendable {
    var onActiveChange: (@Sendable (Bool) -> Void)? { get set }
    var isActive: Bool { get }

    func start()
    func stop()
}
