// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Foundation

@objc(LBRNAppleNativeArtifactIdentity)
@objcMembers
public final class NativeArtifactIdentity: NSObject, @unchecked Sendable {
    public let projectId: String
    @nonobjc public let release: String
    public let environment: String
    public let service: String

    public init(
        projectId: String,
        release: String,
        environment: String,
        service: String,
    ) throws {
        guard UUID(uuidString: projectId)?.uuidString.lowercased() == projectId,
              Self.isExactContext(release),
              Self.isExactContext(environment),
              Self.isExactContext(service)
        else {
            throw NativeCrashError(.invalidConfiguration)
        }
        self.projectId = projectId
        self.release = release
        self.environment = environment
        self.service = service
        super.init()
    }

    override public func isEqual(_ object: Any?) -> Bool {
        guard let other = object as? NativeArtifactIdentity else {
            return false
        }
        return projectId == other.projectId
            && release == other.release
            && environment == other.environment
            && service == other.service
    }

    override public var hash: Int {
        var hasher = Hasher()
        hasher.combine(projectId)
        hasher.combine(release)
        hasher.combine(environment)
        hasher.combine(service)
        return hasher.finalize()
    }

    override public var description: String {
        "NativeArtifactIdentity(configured: true)"
    }

    private static func isExactContext(_ value: String) -> Bool {
        guard (1 ... 256).contains(value.utf8.count),
              value == value.trimmingCharacters(in: .whitespacesAndNewlines),
              !value.unicodeScalars.contains(where: CharacterSet.controlCharacters.contains)
        else {
            return false
        }
        return true
    }
}

struct NativeArtifactIdentityValue: Codable, Equatable {
    private static let reportKey = "logbrew_native_artifact_identity"
    private static let reportFields = [
        "environment",
        "project_id",
        "release",
        "service",
        "version",
    ]

    let projectId: String
    let release: String
    let environment: String
    let service: String

    init(_ identity: NativeArtifactIdentity) {
        projectId = identity.projectId
        release = identity.release
        environment = identity.environment
        service = identity.service
    }

    func validatedIdentity() throws -> NativeArtifactIdentity {
        try NativeArtifactIdentity(
            projectId: projectId,
            release: release,
            environment: environment,
            service: service,
        )
    }

    var crashUserInfoJSON: [String: Any] {
        [
            Self.reportKey: [
                "version": 1,
                "project_id": projectId,
                "release": release,
                "environment": environment,
                "service": service,
            ],
        ]
    }

    static func persistedIdentity(in rawReport: [String: Any]) throws -> NativeArtifactIdentity? {
        guard let user = rawReport["user"] as? [String: Any],
              let persisted = user[reportKey]
        else {
            return nil
        }
        guard let values = persisted as? [String: Any],
              values.keys.sorted() == reportFields,
              values["version"] as? Int == 1,
              let projectId = values["project_id"] as? String,
              let release = values["release"] as? String,
              let environment = values["environment"] as? String,
              let service = values["service"] as? String
        else {
            throw NativeCrashError(.reportCorrupt)
        }
        do {
            return try NativeArtifactIdentity(
                projectId: projectId,
                release: release,
                environment: environment,
                service: service,
            )
        } catch {
            throw NativeCrashError(.reportCorrupt)
        }
    }
}
