// Generated by scripts/sync-apple-native-sources.mjs.
// Edit the canonical Swift source, then regenerate this package boundary.
import Darwin
import Foundation
@preconcurrency import KSCrash

final class NativeMainThreadStackCapture: MainThreadStackCapturing, @unchecked Sendable {
    private static let maxFrames = 32
    private static let cpuTypeArm64: Int32 = 0x0100_000C
    private static let cpuTypeX8664: Int32 = 0x0100_0007
    private static let cpuSubtypeMask: UInt32 = 0x00FF_FFFF
    private let mainThread: pthread_t

    init() throws {
        guard Thread.isMainThread else {
            throw NativeCrashError(.invalidConfiguration)
        }
        mainThread = pthread_self()
    }

    func capture() -> [NativeStackFrame] {
        #if os(watchOS)
            return []
        #else
            var addresses = [UInt](repeating: 0, count: Self.maxFrames)
            let count = captureBacktrace(
                thread: mainThread,
                addresses: &addresses,
                count: Int32(Self.maxFrames),
            )
            guard count > 0 else {
                return []
            }
            return addresses.prefix(Int(count)).compactMap(frame)
        #endif
    }

    private func frame(for address: UInt) -> NativeStackFrame? {
        var information = SymbolInformation()
        guard symbolicate(address: address, result: &information),
              let uuidBytes = information.imageUUID,
              let architecture = architecture(
                  cpuType: information.imageCpuType,
                  cpuSubtype: information.imageCpuSubType,
              ),
              information.callInstruction >= information.imageAddress
        else {
            return nil
        }
        let imageEnd = information.imageAddress.addingReportingOverflow(UInt(information.imageSize))
        guard !imageEnd.overflow, information.callInstruction < imageEnd.partialValue else {
            return nil
        }
        let bytes = UnsafeBufferPointer(start: uuidBytes, count: 16)
        let uuid = UUID(uuid: (
            bytes[0], bytes[1], bytes[2], bytes[3],
            bytes[4], bytes[5], bytes[6], bytes[7],
            bytes[8], bytes[9], bytes[10], bytes[11],
            bytes[12], bytes[13], bytes[14], bytes[15],
        )).uuidString.lowercased()
        return NativeStackFrame(
            imageUuid: uuid,
            architecture: architecture,
            instructionOffset: String(
                format: "%016llx",
                UInt64(information.callInstruction - information.imageAddress),
            ),
        )
    }

    private func architecture(cpuType: Int32, cpuSubtype: Int32) -> NativeStackArchitecture? {
        let subtype = UInt32(bitPattern: cpuSubtype) & Self.cpuSubtypeMask
        return switch (cpuType, subtype) {
        case (Self.cpuTypeArm64, 0), (Self.cpuTypeArm64, 1):
            .arm64
        case (Self.cpuTypeArm64, 2):
            .arm64e
        case (Self.cpuTypeX8664, 3):
            .x8664
        default:
            nil
        }
    }
}
