import * as core from "./index.js";

export type {
  ActionAttributes,
  BaggageEntry,
  ConsoleCaptureConfig,
  ConsoleCaptureHandle,
  ConsoleLike,
  ConsoleMethodName,
  CurrentOpenTelemetryTraceContextOptions,
  DeliveryHealthSnapshot,
  DroppedEvent,
  EnvironmentAttributes,
  Event,
  EventFilter,
  EventStore,
  IssueAttributes,
  IssueStackFrame,
  JavaScriptErrorIssueOptions,
  LogAttributes,
  LogCorrelationTraceContext,
  Metadata,
  MetadataValue,
  MetricAttributes,
  NetworkMilestoneInput,
  OpenTelemetryApiLike,
  OpenTelemetryExportResult,
  OpenTelemetryHrTimeLike,
  OpenTelemetryReadableSpanLike,
  OpenTelemetryReadableSpanOptions,
  OpenTelemetrySpanContextLike,
  OpenTelemetrySpanExporterConfig,
  OpenTelemetrySpanExporterHandle,
  OpenTelemetrySpanLike,
  OpenTelemetrySpanLinkLike,
  OpenTelemetrySpanProcessorConfig,
  OpenTelemetrySpanProcessorHandle,
  OpenTelemetryTimedEventLike,
  OpenTelemetryTraceContextOptions,
  PinoDestinationConfig,
  PinoDestinationHandle,
  PinoLogRecord,
  ProductActionInput,
  ReleaseAttributes,
  Severity,
  SeverityAlias,
  SeverityInput,
  SpanAttributes,
  SpanEventSummary,
  SpanLinkSummary,
  StoredEvent,
  SupportDiagnosticsValue,
  SupportTicketCategory,
  SupportTicketDraft,
  SupportTicketDraftInput,
  SupportTicketSource,
  TimelineAttributesOptions,
  TraceContextInput,
  TraceparentContext,
  TraceparentInput,
  TraceparentSpanInput,
  TracestateEntry,
  Transport,
  TransportResponse
} from "./index.js";

export {
  createBaggage,
  createIssueAttributesFromError,
  createLogBrewOpenTelemetrySpanExporter,
  createLogBrewOpenTelemetrySpanProcessor,
  createLogBrewPinoDestination,
  createNetworkMilestoneAttributes,
  createProductActionAttributes,
  createSupportTicketDraft,
  createTraceContextHeaders,
  createTraceparent,
  createTraceparentHeaders,
  createTracestate,
  installLogBrewConsoleCapture,
  LogBrewClient,
  logAttributesFromConsoleArgs,
  logAttributesFromPinoRecord,
  logbrewLevelFromConsoleMethod,
  logbrewTraceContextFromCurrentOpenTelemetrySpan,
  logbrewTraceContextFromOpenTelemetrySpan,
  logbrewTraceContextFromOpenTelemetrySpanContext,
  parseBaggage,
  parseTraceparent,
  parseTracestate,
  RecordingTransport,
  SdkError,
  spanAttributesFromOpenTelemetryReadableSpan,
  spanAttributesFromTraceparent,
  TransportError
} from "./index.js";

declare const sdk: Omit<
  typeof core,
  "createLogBrewWinstonTransport" | "logAttributesFromWinstonInfo"
>;

export default sdk;
