#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
package_dir="$repo_root/swift/logbrew-swift"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

swift build --package-path "$package_dir" --scratch-path "$tmp_dir/build" >/dev/null
swift test --package-path "$package_dir" --scratch-path "$tmp_dir/test" >/dev/null

archive_path="$tmp_dir/logbrew-swift-source.zip"
swift package --package-path "$package_dir" --scratch-path "$tmp_dir/archive" archive-source --output "$archive_path" >/dev/null
test -f "$archive_path"
unzip -Z1 "$archive_path" > "$tmp_dir/archive-contents.txt"
grep -q '/Package.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/README.md$' "$tmp_dir/archive-contents.txt"
grep -q '/.swiftformat$' "$tmp_dir/archive-contents.txt"
grep -q '/.swiftlint.yml$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/EventEncoding.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DurableDeliveryStore.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DurableDeliveryStoreRecovery.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DeliveryEngine.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DeliveryEngineDurable.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DeliveryEngineAutomatic.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DeliveryEngineQueue.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/DeliveryLifecycle.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/LifecycleTrace.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/LogBrewClient.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/LogBrewLogger.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/LogBrewTrace.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/Metadata.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/ProductTimeline.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/PublicTypes.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/Transport.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/URLSessionTrace.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrew/Validation.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrewCrash/CrashEngine.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrewCrash/CrashReportSanitizer.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrewCrash/CrashStorageDirectory.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrewCrash/NativeCrashCapture.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/LogBrewCrash/NativeCrashPublic.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/ReadmeExample/main.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/RealUserSmoke/main.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Sources/TraceCorrelationExample/main.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/LogBrewTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/AutomaticDeliveryTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/AutomaticDeliveryLifecycleTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/AutomaticDeliveryTestSupport.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/DurableDeliveryPublicContractTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/DurableDeliveryFailureTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/DurableDeliveryRecoveryTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewCrashTests/NativeCrashCaptureTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewCrashTests/NativeCrashDeliveryTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewCrashTests/CrashTestSupport.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/LifecycleTraceTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/OpenTelemetryTraceContextTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/Tests/LogBrewTests/TraceContextTests.swift$' "$tmp_dir/archive-contents.txt"
grep -q '/examples/Makefile$' "$tmp_dir/archive-contents.txt"
unzip -p "$archive_path" '*/README.md' > "$tmp_dir/archive-readme.md"
grep -q 'HTTPTransport' "$tmp_dir/archive-readme.md"
grep -q 'LogBrewLogger' "$tmp_dir/archive-readme.md"
grep -q 'client.metric' "$tmp_dir/archive-readme.md"
grep -q 'MetricAttributes' "$tmp_dir/archive-readme.md"
grep -q 'LogBrewTrace' "$tmp_dir/archive-readme.md"
grep -q 'OpenTelemetry' "$tmp_dir/archive-readme.md"
grep -q 'LogBrewLifecycleTracker' "$tmp_dir/archive-readme.md"
grep -q 'captureLifecycleSpan' "$tmp_dir/archive-readme.md"
grep -q 'startURLSessionSpan' "$tmp_dir/archive-readme.md"
grep -q 'LOGBREW_API_KEY' "$tmp_dir/archive-readme.md"
grep -q 'LogBrewCrash' "$tmp_dir/archive-readme.md"
grep -q 'NativeCrashCapture' "$tmp_dir/archive-readme.md"
grep -q 'Native frame upload and hosted symbolication are not part of this feature' "$tmp_dir/archive-readme.md"
grep -q 'startAutomaticDelivery' "$tmp_dir/archive-readme.md"
grep -q 'Durable Delivery (Opt-In)' "$tmp_dir/archive-readme.md"
grep -q 'enableDurableDelivery' "$tmp_dir/archive-readme.md"
grep -q 'purgeDurableDelivery' "$tmp_dir/archive-readme.md"
grep -q 'deliveryHealth' "$tmp_dir/archive-readme.md"
unzip -p "$archive_path" '*/Sources/LogBrew/LifecycleTrace.swift' > "$tmp_dir/archive-lifecycle.swift"
grep -q 'LogBrewLifecycleTracker' "$tmp_dir/archive-lifecycle.swift"
grep -q 'captureTransition' "$tmp_dir/archive-lifecycle.swift"
unzip -p "$archive_path" '*/Sources/LogBrew/LogBrewTrace.swift' > "$tmp_dir/archive-trace.swift"
grep -q 'LogBrewOpenTelemetrySpanContext' "$tmp_dir/archive-trace.swift"
grep -q 'openTelemetrySpanContext' "$tmp_dir/archive-trace.swift"
grep -q 'context(fromOpenTelemetrySpanContext' "$tmp_dir/archive-trace.swift"
grep -q 'spanAttributesFromOpenTelemetrySpanContext' "$tmp_dir/archive-trace.swift"
unzip -p "$archive_path" '*/Sources/TraceCorrelationExample/main.swift' > "$tmp_dir/archive-trace-example.swift"
grep -q 'openTelemetrySpanContext' "$tmp_dir/archive-trace-example.swift"
grep -q 'LogBrewLifecycleTracker' "$tmp_dir/archive-trace-example.swift"

echo "swift package checks passed"
