const PLUGIN_NAME = "@logbrew/react-native/expo";
const START_MARKER = "  # @generated by @logbrew/react-native/expo";
const END_MARKER = "  # @end @logbrew/react-native/expo";
const POD_BLOCK = [
  START_MARKER,
  "  logbrew_react_native_path = File.dirname(`node --print \"require.resolve('@logbrew/react-native')\"`)",
  "  pod 'LogBrewReactNative/AppleNativeDiagnostics', :path => logbrew_react_native_path",
  END_MARKER
].join("\n");

function withLogBrewReactNative(config, options = {}) {
  const { withPodfile } = require("expo/config-plugins");
  return withPodfile(config, (podfileConfig) => {
    podfileConfig.modResults.contents = modifyPodfile(
      podfileConfig.modResults.contents,
      options?.appleNativeDiagnostics !== false
    );
    return podfileConfig;
  });
}

function modifyPodfile(contents, enabled = true) {
  if (typeof contents !== "string") {
    throw new TypeError(`${PLUGIN_NAME} expected Podfile text`);
  }
  const withoutManagedBlock = contents.replace(
    new RegExp(`${escapePattern(START_MARKER)}[\\s\\S]*?${escapePattern(END_MARKER)}\\n?`, "gu"),
    ""
  );
  if (!enabled) {
    return withoutManagedBlock;
  }
  const targetPattern = /^(target\s+['"][^'"]+['"]\s+do\s*)$/mu;
  if (!targetPattern.test(withoutManagedBlock)) {
    throw new Error(`${PLUGIN_NAME} could not locate an iOS application target in the Podfile`);
  }
  return withoutManagedBlock.replace(targetPattern, `$1\n${POD_BLOCK}`);
}

function escapePattern(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

module.exports = withLogBrewReactNative;
module.exports.modifyPodfile = modifyPodfile;
module.exports.withLogBrewReactNative = withLogBrewReactNative;
