const PLUGIN_NAME = "@logbrew/react-native/expo";
const START_MARKER = "  # @generated by @logbrew/react-native/expo";
const END_MARKER = "  # @end @logbrew/react-native/expo";
const MANAGED_BLOCK = /  # @generated by @logbrew\/react-native\/expo[\s\S]*?  # @end @logbrew\/react-native\/expo\n?/gu;
const POD_BLOCK = [
  START_MARKER,
  "  require 'pathname'",
  "  logbrew_react_native_path = Pathname(File.dirname(`bun --print \"require.resolve('@logbrew/react-native')\"`)).relative_path_from(Pathname(__dir__)).to_s",
  "  pod 'LogBrewReactNative/AppleNativeDiagnostics', :path => logbrew_react_native_path",
  END_MARKER
].join("\n");

function withLogBrewReactNative(config, options = {}) {
  const { withPodfile } = require("expo/config-plugins");
  const enabled = options?.appleNativeDiagnostics !== false;
  return withPodfile(config, podfileConfig => {
    const podfile = podfileConfig.modResults;
    podfile.contents = modifyPodfile(podfile.contents, enabled);
    return podfileConfig;
  });
}

function modifyPodfile(contents, enabled = true) {
  if (typeof contents !== "string") {
    throw new TypeError(`${PLUGIN_NAME} expected Podfile text`);
  }
  const withoutManagedBlock = contents.replace(MANAGED_BLOCK, "");
  if (!enabled) {
    return withoutManagedBlock;
  }
  const targetPattern = /^(target\s+['"][^'"]+['"]\s+do\s*)$/mu;
  if (!targetPattern.test(withoutManagedBlock)) {
    throw new Error(`${PLUGIN_NAME} could not locate an iOS application target in the Podfile`);
  }
  return withoutManagedBlock.replace(targetPattern, `$1\n${POD_BLOCK}`);
}

module.exports = withLogBrewReactNative;
module.exports.modifyPodfile = modifyPodfile;
module.exports.withLogBrewReactNative = withLogBrewReactNative;
